"""
tests/test_normalize_parity.py — W7-3 normalize_spot_name の Python↔JS parity fixture

設計準拠:
  - W7-3_設計案決裁_司令塔5_20260420.md Q4（parity 軽量版）
  - 計画書_司令塔5_釣り場分類人機協調改革_20260420.md §3-3, §3-4
  - 指示書_W7-3_collector_html_レビューUI_20260420.md §4-3

目的:
  collector.html の `normalizeSpotNameJs()`（JS 側）と、
  engines.spot_classifier.SpotClassifier.normalize_spot_name()（Python 側）が
  同じ入力に対して同じ出力を返すことの「証拠」となる fixture を生成・検証する。

仕組み:
  - Python 側: 本ファイル実行 or pytest 実行 で fixture（tests/fixtures/normalize_parity_cases.json）を
    保持、各ケースに対し normalize_spot_name(input) が expected と一致することを検証する
  - JS 側: collector.html 起動時に URL パラメータ `?parity=1` が付いていれば、
    fetch でこの fixture を読み、各 case に normalizeSpotNameJs() を適用し、
    mismatch があれば console.error() と画面 toast で警告する

CI 統合:
  なし（現行 CI は Python のみ、本ファイルは pytest で回帰するが、
  JS 側の parity check は手動・開発時起動のみ）

fixture 再生成:
  CLI 実行で上書き保存（CI では絶対に走らない）:
    python -m tests.test_normalize_parity --regenerate
  通常 pytest 実行では fixture ファイルを上書きしない。

ケース構成（合計 36 例、決裁書 §Q4「30 例以上」要件を満たす）:
  1. spot_canonical_rules の rules.from 全 21 件
  2. master_catch.csv の spot 列上位 10 件（2026-04-20 時点の出現頻度）
  3. 異常系 5 件（空文字列、長文、英数字混在、半角全角混在、括弧・空白）
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from engines.spot_classifier import SpotClassifier


# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
_STATIONS = _REPO_ROOT / "data" / "b_mapping" / "stations_master.json"
_RULES = _REPO_ROOT / "data" / "b_mapping" / "spot_canonical_rules.json"
_FIXTURE_PATH = _REPO_ROOT / "tests" / "fixtures" / "normalize_parity_cases.json"


# ------------------------------------------------------------
# Input set（36 例）
# ------------------------------------------------------------
# Group 1: 既存 spot_canonical_rules.rules の from 全 21 件（W2-2 時点）
_INPUTS_RULES_FROM: list[str] = [
    "室戸沖磯",
    "室戸磯",
    "室戸地磯",
    "地磯",
    "室戸港内",
    "室戸港",
    "室戸沖港",
    "室戸近場",
    "室戸沖近場",
    "室戸近海",
    "室戸岬沖",
    "室戸岬近海",
    "室戸沖岬沖",
    "室戸沖周辺",
    "室戸沖周辺散歩がてら",
    "室戸沖風裏",
    "室戸沖風浦",
    "甲浦風裏",
    "安満地風裏",
    "小笠原沖",
    "小笠原諸島",
]

# Group 2: master_catch.csv spot 列上位 10 件（2026-04-20 時点の出現頻度観察）
#   実入力（県名プレフィックスや括弧を含むもの）を混ぜ、normalize の実働ケースを作る
_INPUTS_MASTER_SAMPLE: list[str] = [
    "室戸沖",
    "高知室戸沖",
    "安満地",
    "甲浦",
    "室戸近場",
    "高知 安満地",  # 半角スペース付き
    "室戸沖（近場）",  # 全角括弧
    "高知室戸沖（風浦）",
    "室戸（磯）",
    "甲浦（風裏）",
]

# Group 3: 異常系 5 件
_INPUTS_EDGE: list[str] = [
    "",  # 空文字列
    "   ",  # 全角/半角空白のみ → Step2 後に "" → 空ケース
    "A" * 120,  # 長文（英字）
    "Test テスト 123　４５６",  # 英数・和字・半角全角混在
    "　高知県 　（室戸沖） \t",  # 複雑なホワイトスペース・括弧・県名
]

_ALL_INPUTS: list[str] = _INPUTS_RULES_FROM + _INPUTS_MASTER_SAMPLE + _INPUTS_EDGE


# ------------------------------------------------------------
# Fixture build
# ------------------------------------------------------------
def _build_cases(clf: SpotClassifier) -> list[dict]:
    """各入力に対し expected（normalize_spot_name の出力）を添えた case リストを作る."""
    cases: list[dict] = []
    for s in _ALL_INPUTS:
        cases.append({"input": s, "expected": clf.normalize_spot_name(s)})
    return cases


def _load_fixture() -> dict | None:
    if not _FIXTURE_PATH.exists():
        return None
    with _FIXTURE_PATH.open(encoding="utf-8") as f:
        return json.load(f)


def _save_fixture(doc: dict) -> None:
    _FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with _FIXTURE_PATH.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
        f.write("\n")


def _regenerate() -> None:
    """fixture ファイルを最新の normalize_spot_name 出力で上書き保存する。CLI から呼ぶ."""
    clf = SpotClassifier(str(_STATIONS), str(_RULES))
    cases = _build_cases(clf)
    doc = {
        "description": (
            "W7-3 normalize_spot_name parity fixture. "
            "Generated by Python; consumed by collector.html normalizeSpotNameJs() "
            "via URL ?parity=1 for visual dev-mode verification. "
            "See W7-3_設計案決裁_司令塔5_20260420.md Q4."
        ),
        "python_source": "engines.spot_classifier.SpotClassifier.normalize_spot_name",
        "case_count": len(cases),
        "groups": {
            "rules_from": len(_INPUTS_RULES_FROM),
            "master_sample": len(_INPUTS_MASTER_SAMPLE),
            "edge": len(_INPUTS_EDGE),
        },
        "cases": cases,
    }
    _save_fixture(doc)
    print(f"Regenerated fixture: {_FIXTURE_PATH}")
    print(f"  case_count = {len(cases)}")


# ------------------------------------------------------------
# Tests
# ------------------------------------------------------------
def test_fixture_file_exists():
    """fixture がリポジトリにコミットされている."""
    assert _FIXTURE_PATH.exists(), (
        f"{_FIXTURE_PATH} が存在しない。"
        " CLI `python -m tests.test_normalize_parity --regenerate` で生成してコミットしてください。"
    )


def test_fixture_has_minimum_cases():
    """決裁書 §Q4：30 例以上."""
    doc = _load_fixture()
    assert doc is not None
    assert doc.get("case_count", 0) >= 30, "fixture の case 数が 30 未満"
    assert len(doc.get("cases", [])) >= 30


def test_fixture_cases_match_current_normalize():
    """fixture の expected が、現在の normalize_spot_name 出力と一致する."""
    doc = _load_fixture()
    assert doc is not None

    clf = SpotClassifier(str(_STATIONS), str(_RULES))
    mismatches: list[dict] = []
    for case in doc["cases"]:
        actual = clf.normalize_spot_name(case["input"])
        if actual != case["expected"]:
            mismatches.append(
                {
                    "input": case["input"],
                    "expected": case["expected"],
                    "actual": actual,
                }
            )

    assert not mismatches, (
        f"{len(mismatches)} 件の mismatch: {mismatches[:3]}\n"
        "fixture と現在の normalize_spot_name 出力が乖離しています。"
        " ロジック変更が意図的なら CLI --regenerate で fixture を更新してコミットしてください。"
    )


def test_input_set_coverage():
    """入力セットが主要3グループを網羅している（テストメタ健全性）."""
    # Group 1: rules.from 全件
    assert len(_INPUTS_RULES_FROM) == 21
    # Group 2: master_catch 上位サンプル
    assert len(_INPUTS_MASTER_SAMPLE) == 10
    # Group 3: 異常系
    assert len(_INPUTS_EDGE) == 5
    assert len(_ALL_INPUTS) == 36


def test_edge_empty_string_returns_empty():
    """空文字列入力は normalize 後も空文字列（sentinel の基盤）."""
    clf = SpotClassifier(str(_STATIONS), str(_RULES))
    assert clf.normalize_spot_name("") == ""


# ------------------------------------------------------------
# CLI
# ------------------------------------------------------------
if __name__ == "__main__":
    if "--regenerate" in sys.argv:
        _regenerate()
        sys.exit(0)
    sys.exit(pytest.main([__file__, "-v"]))
